### ISSUE TITLE
Configure volume for containers

### ISSUE THREAD

**Issue by waaghals** [waaghals/toip#23]
- [ ] Allow absolute paths configured in user config
- [ ] Error when volume is not known in main config

Example configuration:
```yaml
# toip.yaml
containers:
  container_with_volumes:
    image: ...
    volumes:
      /absolute/path/in/container: volume_a
      /path: volume_b

  other_container:
    image: ...
    mounts:
      /path: volume_b
      /other/path: volume_c

volumes:
  volume_a:
    source: relative/path/relative/to/config/file
    readonly: true
  volume_b: 
    source: shared/between/containers
  volume_c:
    name: anonymous
  volume_d:
    name: ${ENV_VAR}
    external: true
  volume_e: 
    source: ${HOME}/in/home/dir
```
