### ISSUE TITLE
Modify configuration using .env substitution

### ISSUE THREAD

**Issue by waaghals** [waaghals/toip#30]
Allow values to be env substituted. Loads .env and uses processes available env vars.

Example:
```yaml
aliases:
  ...
containers:
  container_a:
    image:
      context: .
      target: ${TARGET}
    cmd: ${COMMAND_TARGET}
    volumes:
      /app: ${VOLUME_NAME:-path_substitution}
    env:
      CONTAINER_VARIABLE: ${ENV_FROM_HOST}
    workdir: ${WORKDIR}
  container_b:
    image: some_image:${TAG}
  container_c:
    image: ${IMAGE}
volumes:
  path_substitution:
    source: ${PATH}/more
    readonly: true
  name_substitution:
    name: ${VOLUME_NAME?missing volume}
```
